# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Identify Release Type
        run: echo "VSCE_PRE_RELEASE_FLAG=${{ github.event.release.prerelease && '--pre-release' || '' }}" >> $GITHUB_ENV
      - name: Clean Install
        run: npm ci
      - name: Generate Version
        run: npm link semver && npm version $(node version.js)
      - name: Build Package
        run: npx vsce package -o vscode-vault.vsix $VSCE_PRE_RELEASE_FLAG
      - name: Publish Release
        run: npx vsce publish --packagePath artifact/vscode-vault.vsix $VSCE_PRE_RELEASE_FLAG
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

  bump:
    runs-on: ubuntu-latest
    if: github.event.release.prerelease == false
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Bump Version
        run: npm version minor --git-tag-version=false
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
          commit-message: Prepare for next development iteration
          base: main
